### ISSUE TITLE
Keep ESP32 build?

### ISSUE THREAD

**Issue by floatplane** [floatplane/mitsubishi2MQTT#18]
I'm not using it, not testing it, maybe not worth it

**Comment by xury77** [comment]
You could keep if is not a problem for you. I think is much easier to build HW on ESP32 devices.

**Comment by floatplane** [comment]
Sounds good @xury77, I'll leave it for now. I just don't have hardware to test it so I wasn't sure if it was useful. 

It's maybe not great that we're only building debug builds for ESP32, but I'll worry about that another time!
